# Generated by Django 5.1.6 on 2025-02-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='address_line1',
            new_name='address',
        ),
    ]
